gonum/graph

concrete/mutablegr.go
concrete/mutablegr_test.go
concrete/mutdir.go
graph.go
search/graph_search.go

This allows the ID of the node to be used in place of the returned node,
or the returned node to be placed in a graph.Node embedded field prior
to adding the wrapping struct.
@btracey @Jragonmiris @gonum/developers PTAL

Defer adding new nodes to graph

---

search/graph_search.go
search/internals.go

The previous code was giving incorrect results for a 2SAT solver I have
built on it (cannot release). This fixes that.
Tests to come.

Fix Tarjan implementation

---

traverse/traverse.go
traverse/traverse_test.go

This adds a new package, traverse, that provides basic and very generalisable stateful graph traversal primitives. These are intended to be used as building blocks for broader algorithms, e.g. connected components would use a Walk methods in conjunction with the associated Visited method to avoid continual reallocation of visited structures.
We already have a DepthFirstSearch function in search and AStar may be used as breadth first, but these return paths, rather than allowing arbitrary operations on the traversed edges and node. Additionally, AStar is much heavier than a simple breadth-first.

graph/traverse: new package - basic traversal primitives

---

search/johnson_cycles.go
search/johnson_cycles_test.go

There are potential optimisations here in replacing the johnson.nodeMap with functionality provided by johnsonGraphNode. But I will leave that for later.
@soniakeys @Jragonmiris

search: add Johnson's elementary cycles finding function

---

network/hits.go
network/hits_test.go
network/network.go
network/network_test.go
network/page.go
network/page_test.go

network: new package implement PageRank and HITS

---

internal/set.go
internal/sort.go
search/graph_search.go
search/johnson_cycles.go
search/johnson_cycles_test.go
search/search_test.go
search/set.go
traverse/traverse.go
traverse/traverse_test.go

Add internal package for (most) shared unexported types and factor test example graphs into named values.

{search,traverse}: clean up after recent changes

---

concrete/tilegraph.go
internal/tilegraph.go
internal/tilegraph_test.go
search/search_test.go

This is a small set of changes that allows TileGraph to interact with encoding cleanly and reduces the string operation load.
In the long run it would be nice to know where this kind of graph is going to be used. I think that marshaling as pretty runes is probably a wrong thing to do - a Render function would be more appropriate to handle that.

Tile cleanup

---

search/graph_search.go

Fixes #61.
Looks like I was sharing without caring. I don't really understand why this never fails on previous runtimes.

search: fix BronKerbosch on Go tip

---

network/betweenness.go
network/betweenness_test.go
network/distance.go
network/distance_test.go

This brings the general case for betweenness (though see below) and various centrality measures.
Currently we perform poorly for sparse graphs since we use FloydWarshal's algorithm to find shortest paths. One approach to address this would be for the functions here that take a search.ShortestPaths to take an equivalent interface (or a reduced interface for the centrality measures that only need weights) and then make search.Johnson return a type that satisfies this instead of a pair of maps. I don't want to do this because although it is an easy solution for the centrality measures it will give incorrect results for betweenness when there are non-unique shortest paths; the current implementation of Dijkstra's algorithm in search does not report more than one shortest path. So I plan to …

network: add more network analysis measures

---

concrete/mutablegr.go
concrete/mutdir.go

Updates #53.
@gonum/developers

concrete: don't return a different Edge type than was added

---

encoding/dot/dot.go
encoding/dot/dot_test.go

~~Currently, the package handles our basic graph types without any problem, but there are features in DOT that we can use (the additional interfaces do this - though they are not yet tested), e.g. subgraphs.~~
When this has been iterated over, I will write a DOT parser to do the unmarshaling (this has some hairy bits that I'm still thinking about, but it's less of a concern - I just want something to make our packages a bit more friendly for visualisation).
@gonum/developers

encoding/dot: new package DOT graph encoding

---

encoding/dot/dot.go
encoding/dot/dot_test.go

I'm writing the ragel grammar for a parser and noticed what I should have seen before; the name is optional. I have left graph.Node ID and dot.Node ID naming for subgraphs unless the client implements a DOTID() string that returns "".
@vladimir-ch

encoding/dot: don't enforce naming graph

---

concrete/mutablegr.go
concrete/mutdir.go
graph.go
network/betweenness_test.go
network/distance_test.go
network/hits_test.go
network/page_test.go
search/johnson_cycles_test.go
search/search_test.go
traverse/traverse_test.go

This is consistent with our approaches to flexibility in matrix and blas. We don't allow potentially unsafe things to go unnoticed.
@gonum/developers PTAL

{graph,concrete}: make node ID collision be a panic

---

search/floydwarshall.go
search/floydwarshall_test.go

* Allow FloydWarshall to write zero length cycles.
* Make Between excise zero-length cycles but mark as non-unique.
* Make AllBetween drop paths that extend into zero-length cycles.
This is option 2 in #72.
The recursive path reconstruction is a little subtle, but I think correct.
@vladimir-ch

search: fix handling of zero-weight cycle case

---

search/floydwarshall_test.go

I had intended the competitors to be stellate, but copy-paste undid me. The result is a good test, so it's kept and named, with the stellate graph added.
@vladimir-ch

search: fix zero-weight cycle tests

---

search/graph_search.go
search/search_test.go

Fixes #78.
The naming might be contentious. The thinking is that TarjanSCC and this will end up in the `structure` package (that I am now thinking should be called `topo`for shortness) - the contents of which might look something like it does in api-explore.
We could just do a DFS toposort, but I think the value of being able to provide a reason for failure is worth any additional computational cost. The maintenance cost is 0, since we already need to look after TarjanSCC anyway.
@gonum/developers PTAL

search: add topological sort helper function

---

path/a_star.go
path/a_star_test.go
path/shortest.go

Mainly this adds A* returning a Shortest instead of a slice of nodes and weights, but we also add tests and improve performance.
@vladimir-ch PTAL

path: harmonise the A* API with other path algorithm implementations

---

path/a_star_test.go
path/spanning_tree.go
path/spanning_tree_test.go

* Replace incorrect Prim's implementation.
* Make functions return weight.
* Drop default to uniform cost function since this is essentially meaningless here.
Note that I had a map-free implementation that this is derived from, but again the acounting needs to be done on a modified node and so would require a copy of the entire graph. This is easier.
If you would like me to add a check for the actual structure of the MST, I'll add that.

path: add tests for minimum spanning tree functions

---

network/betweenness.go
network/betweenness_test.go
network/page_test.go

Note that the implementation differs from the algorithm published in http://algo.uni-konstanz.de/publications/b-vspbc-08.pdf in that the final condition of algorithm 7 is omitted; it appears to be a copy paste error in the paper in that it is type mismatched (C_B is indexed in this assignment by node, but the algorithm is intended to collect edge-wise data), and omitting it gives the correct answer.

network: add edge betweenness calculation functions

---

graph.go
path/dynamic/dstarlite.go
path/internal/testgraphs/shortest.go
path/spanning_tree.go
path/spanning_tree_test.go
simple/undirected_test.go

graph.Mutable was previously used primarily to add nodes and edges, so
it is not sensible to require that edge and node deletion also be
implemented - there are add-only graph implementations that gain
possible optimisations by this change.
This change also potentially paves the way for multigraph addition with
an EdgeAdder interface.
Also drop the fictional distinction between the two Copy functions.
@vladimir-ch Please take a look - this was a much smaller change than I was expecting.

graph: split mutation API into smaller interfaces

---

ex/fdpclust/gn.go
graph.go
graphs/gen/batagelj_brandes.go
graphs/gen/batagelj_brandes_test.go
graphs/gen/gen.go
graphs/gen/holme_kim.go
graphs/gen/small_world.go
path/dynamic/dstarlite_test.go
path/internal/grid.go
path/internal/limited.go
path/internal/limited_test.go
path/johnson_apsp.go
path/spanning_tree.go
simple/dense_directed_matrix.go
simple/dense_undirected_matrix.go
simple/directed.go
simple/undirected.go
topo/johnson_cycles.go
topo/topo.go

The new name is clearer with respect to the semantics of the method and removing HasEdge allows implementations to add a HasEdge(graph.Edge) method.
Suggested off-line by Vladimir.

all: rename HasEdge -> HasEdgeBetween

---

path/bench_test.go
topo/bench_test.go
topo/tarjan.go
traverse/traverse_test.go

I have looked at similar changes for CyclesIn, but the benefits are mixed, more complicated and incomplete, and clearly not worth the change:
```
name                  old mean              new mean              delta
CyclesInGnp_10_tenth  46.1µs × (1.00,1.00)  44.9µs × (0.98,1.01)   -2.46% (p=0.000 n=9+9)
CyclesInGnp_20_tenth  1.63ms × (1.00,1.00)  1.71ms × (1.00,1.01)  +4.92% (p=0.000 n=10+8)
CyclesInGnp_10_half   8.03ms × (1.00,1.00)  8.14ms × (0.96,1.01)    ~    (p=0.156 n=9+10)
```
Also fix spelling.

topo: use use golang.org/x/.../intsets for TarjanSCC

---

topo/bron_kerbosch.go

This was only in place to stop go1.3 complaining. We no longer support go1.3 for gonum/graph, so remove this.

topo: drop blank range variable assignment

---

community/louvain.go
community/louvain_test.go
internal/ordered/sort.go

This adds the measure used for modularity optimisation. The Louvain, LouvainMultilevel and SLM algorithms will come later.
I'm not sure about the API - the optimisation algorithms may demand a change, but what exists here looks OK for public use with the exception that community memberships must be disjoint and we don't check for that here.
https://en.wikipedia.org/wiki/Louvain_Modularity#Algorithm and http://arxiv.org/abs/cond-mat/0603718 for reference - the latter only for the resolution parameter.

community: new package implement Louvain graph modularisation

---

community/louvain.go

Missed in the change from network to community.
@vladimir-ch Please take a look, in due course.

community: fix panic string package prefix

---

undirect.go

This was an oversight in the Undirect PR.

graph: return all neighbours reachable from u

---

community/louvain.go
community/louvain.tex

Showed that the intuitive extension to directed graphs is actually equivalent to creating an undirected graph by averaging edges in opposite directions. In the process, also showed that the Louvain algorithm is infact invariant to multiplying all edge weights by a non-zero constant (which is good).
@kortschak @vladimir-ch Please take a look.

community: Directed Graph equivalence

---

graphs/gen/duplication.go

graphs/gen: make duplication graph generation reproducible

---

encoding/dot/dot.go

encoding/dot: Fix trimming of whitespace suffix.

---

community/louvain_common.go
community/louvain_directed.go
community/louvain_directed_test.go
community/louvain_test.go
community/louvain_undirected.go
community/louvain_undirected_test.go
community/printgraphs.go

Please take a look at this for glaring errors (most appropriate way would be to `diff -u louvain_undirected.go louvain_directed.go` (possibly with colour magic) to see the changes in the implementation between the two. These changes should reflect the differences in the louvain.tex for the two approaches, Q and Q^(3).
In writing the changes, I found some things in the louvain.text that I am unsure of (recalling discussions with Vincent Traag and reading his code which does handle this case). Notably, I think that m should not be scaled by 2 in the directed case. Lyron is aware of this and will look into when he is back.
Tests need to be added when I have a clue about what they might actually look like.
Please take a look @Armadilloa16, @vladimir-ch.

community: add directed louvain implementation

---

graphs/gen/batagelj_brandes.go

Documentation currently states that if src is nil rand.Float64 is
used however rand.Intn is actually used.
Resolves: #183

graph: Fix documentation for function Gnm

---

path/dijkstra.go

This commit is a first proposal to reduce unnecessary work due to the use of duplicated nodes in the priority queue. Better alternatives could be discussed. What do you think about this ?
If the distance is greater than the value stored in this distance node, then there already exist a better path to reach this node k. Indeed, the priority queue might contain several distanceNode for the same node k (each time it is updated), because this version of the Dijkstra algorithm does not use a decrease-key operation. Therefore, these distanceNodes should be discarded. Otherwise, the adjacent vertices of k could be traversed more than once in the for loop.

path: introduce an optimisation for function DijkstraFrom (proposal)
