search/search_test.go
Clobbered by a rebase on the wrong working machine. Recovered from the
commit ref from travis:
https://travis-ci.org/gonum/graph/builds/51771511
TBR
=> Re-add Tarjan tests

search/graph_search.go, search/non_tomita_choice.go, search/search_test.go, search/set.go, search/set_test.go, search/tomita_choice.go
@soniakeys Please take a look.
Suggestions for the TODO greatfully appreciated.
=> search: add Bron-Kerbosch maximal clique finding function

search/graph_search.go, search/internals.go, search/search_test.go
=> Remove lint

search/graph_search.go, search/search_test.go, traverse/traverse.go, traverse/traverse_test.go
I will clean up the use of the example graph in another PR.
=> search: add connected component finding function

internal/linear.go, network/brandes.go, network/brandes_test.go, search/graph_search.go, search/internals.go, traverse/traverse.go
The results for examples graphs used from previous tests appear correct although I have not rigorously gone through the calculation by hand. The small cases are clearly correct.
@gonum/developers PTAL
=> network: add betweenness centrality function

concrete/dense.go, concrete/densegraph_test.go, graph.go, search/floydwarshall.go, search/floydwarshall_test.go
This is backported from api-explore.
An AllBetween method will be added in a later PR.
@gonum/developers Please take a look.
=> search: fix FloydWarshall

search/floydwarshall.go
This was missed in a previous amendment. Added similar readability improvements to the other methods (suggested by the compiler).
=> search: fix shortest paths weight method

concrete/dense.go, concrete/mutablegr.go, concrete/mutdir.go, graph.go, internal/tilegraph.go, network/betweenness_test.go, network/distance_test.go, network/hits_test.go, network/page_test.go, search/floydwarshall_test.go, search/graph_search.go, search/johnson_cycles.go, search/johnson_cycles_test.go, search/search_test.go, traverse/traverse_test.go
Also remove redundant search.johnsonGraphEdge type.
Fixes #51.
PTAL @vladimir-ch @gonum/developers
=> all: rename Edge methods Head and Tail to From and To

search/graph_search.go, search/search_test.go
=> search: remove BreadthFirstSearch and DepthFirstSearch

search/floydwarshall_test.go
=> search: fix logic for Between test satisfication

search/dijkstra.go, search/dijkstra_test.go, search/floydwarshall.go, search/shortest.go, search/shortest_test.go
I'll squash this into one commit after it's accepted; I want the thinking to be seen in review.
I think it's probably worth renaming ShortestPaths to AllShortest, but I will do that later (in the fullness of time they will be read as path.Shortest and path.AllShortest).
@vladimir-ch
=> search: add DijkstraFrom and DijkstraAllPaths

network/betweenness.go
=> network: fix doc typos

concrete/directed.go, concrete/undirected.go
=> concrete: fix Edges methods for generalised graphs

path/dynamic/dstarlite.go
=> path/dynamic: revise priority queue implementation

concrete/densegraph_test.go, concrete/directed_test.go, concrete/undirected_test.go, concrete/util.go, path/a_star_test.go, path/bellman_ford_moore_test.go, path/dijkstra_test.go, path/floydwarshall_test.go, path/johnson_apsp_test.go, path/shortest_test.go, topo/bron_kerbosch_test.go, topo/common_test.go, topo/johnson_cycles_test.go, topo/tarjan_test.go, topo/topo_test.go, traverse/traverse_test.go
It is not necessary anywhere at the moment.
Fixes #95.
=> all: don't use package_test unless necessary

network/page.go
=> network: use new MulVec signature

graphs/gen/batagelj_brandes.go, graphs/gen/batagelj_brandes_test.go, graphs/gen/gen.go, graphs/gen/holme_kim.go, graphs/gen/holme_kim_test.go, graphs/gen/small_world.go, graphs/gen/small_world_test.go
=> graphs/gen: new package for generating random graphs

traverse/traverse.go, traverse/traverse_test.go
=> traverse: use golang.org/x/.../intsets

simple/dense_directed_matrix.go
=> simple: fix directedness of DirectedDenseGraph.Edge

simple/directed.go, simple/directed_test.go, simple/undirected.go, simple/undirected_test.go
Remove the de-increment of maxID as it is the cause of a panic when we call NewNodeID().
=> Remove the de-increment of maxID as it is the cause of a panic

.travis.yml
Fixes #125.
@gonum/developers Please take a look.
=> travis: delete go1.3.3

encoding/dot/dot.go, internal/linear/linear.go, internal/ordered/sort.go, internal/set/same.go, internal/set/same_appengine.go, internal/set/set.go, internal/set/set_test.go, network/betweenness.go, path/a_star.go, path/control_flow.go, path/dijkstra_test.go, path/floydwarshall_test.go, path/johnson_apsp_test.go, simple/densegraph_test.go, topo/bron_kerbosch.go, topo/bron_kerbosch_test.go, topo/common_test.go, topo/johnson_cycles.go, topo/johnson_cycles_test.go, topo/tarjan.go, topo/tarjan_test.go, topo/topo_test.go, traverse/traverse.go, traverse/traverse_test.go
=> internal: split and clean up

graphs/gen/duplication.go, graphs/gen/duplication_test.go
I am generally avoiding adding biologically motivated functions to graph, but this generator has characteristics that differ from the other generators that we have and I think it has more general utility.
=> graphs/gen: add duplication graph generator

topo/johnson_cycles.go
Fixes #134.
@gonum/developers Please take a look.
=> topo: fix panic messages

graph.go, simple/dense_directed_matrix.go, simple/dense_undirected_matrix.go, simple/densegraph_test.go, simple/directed.go, simple/simple.go, simple/undirected.go
This also adds the possibility of storing nodes in adjacency matrix graphs - though not edges.
=> simple: cleanup docs and definitions

community/louvain.tex
Includes more detail explaining how the maths behind the community 
detection algorithm works. Was abit painful to figure out, so thought
we should share now that we think we understand it, accompanies #133 
@kortschak Could take a look? I made some cosmetic changes since 
the last version of this I showed you, but basically should be the same 
thing.
=> community: add louvain.tex explanatory document

community/louvain.tex
@Armadilloa16 Please take a look.
=> community: add license header

graph.go, undirect.go, undirect_test.go
There are a couple of places this could go; either simple or graph. It seems to me that it's fundamental enough that it should be in graph.
=> graph: add type to allow defined conversion directed -> undirected

community/louvain.go, community/louvain_test.go, undirect.go
I must remember to always include a sparsely ID'd node set test.
=> community: fix a variety of bugs in Louvain and Q

community/louvain.go
This again reduces the amount of unneeded work being done.
The vast majority of the effect comes from the second commit. I don't know what I was thinking when I added the copy.
=> community: improve Louvain performance

community/louvain.go
=> community: add comment about approach for sigma_tot calculation

graphs/gen/holme_kim.go, graphs/gen/small_world.go
=> graphs/gen: update imports

path/bench_test.go
Identified by honnef.co/go/unused.
=> path: fix benchmark call

path/doc.go, path/dynamic/doc.go, topo/topo.go
=> {topo,path,path/dynamic}: add package level docs

community/louvain.tex
As per #160 , and including to typo fixes and some rearrangement for clarity.
Thanks @kortschak for the suggested changes, PTAL?
=> Details for Directed Graph Case

community/louvain_test.go
Clean up missed redundant code.
=> community: run gofmt -s on tests

path/johnson_apsp.go
Missed during the move.
@gonum/developers Please take a look.
=> path: fix panic prefix

community/bisect.go, community/bisect_test.go, community/louvain_common.go, community/louvain_directed.go, community/louvain_directed_multiplex.go, community/louvain_directed_multiplex_test.go, community/louvain_directed_test.go, community/louvain_test.go, community/louvain_undirected.go, community/louvain_undirected_multiplex.go, community/louvain_undirected_multiplex_test.go, community/louvain_undirected_test.go
This needs ~~one test added and for~~ the existing test case expectations to be validated, but they look OK to me.
It's a bit of a doozy, but should be reasonably straightforward if you read it keeping the single layer implementation in mind and that the measure is just the layer weighted sum of layer qualities (and considering the edge weight filtering described in chapter 5 of Vincent Traag's [thesis](http://www.traag.net/wp/wp-content/papercite-data/pdf/traag_algorithms_2013.pdf)).
=> community: add multiplex louvain implementation

topo/tarjan.go, topo/tarjan_test.go
=> topo: add lexically stabilised topological sort

topo/topo.go, topo/topo_test.go
=> topo: add PathExistsIn helper function

graphs/gen/batagelj_brandes.go
Fixes #191.
@jcao219 @vladimir-ch Please take a look.
=> graphs/gen: note the graph models for Gnm and Gnp

path/dijkstra.go
This commit changes complexity based on the reference provided in comments (i.e. http://www.cs.utexas.edu/ftp/techreports/tr07-54.pdf). The previously announced complexity could be reached by using a fibonacci heap and its decrease key operation.
=> path: fix documentation for function DijkstraFrom
